export type JSONWorldContent = {
    DestinyNodeStepSummaryDefinition: Record<string, unknown>
    DestinyArtDyeChannelDefinition: Record<string, unknown>
    DestinyArtDyeReferenceDefinition: Record<string, unknown>
    DestinyPlaceDefinition: Record<string, unknown>
    DestinyActivityDefinition: Record<string, unknown>
    DestinyActivityTypeDefinition: Record<string, unknown>
    DestinyClassDefinition: Record<string, unknown>
    DestinyGenderDefinition: Record<string, unknown>
    DestinyInventoryBucketDefinition: Record<string, unknown>
    DestinyRaceDefinition: Record<string, unknown>
    DestinyTalentGridDefinition: Record<string, unknown>
    DestinyUnlockDefinition: Record<string, unknown>
    DestinySandboxPerkDefinition: Record<string, unknown>
    DestinyStatGroupDefinition: Record<string, unknown>
    DestinyProgressionMappingDefinition: Record<string, unknown>
    DestinyFactionDefinition: Record<string, unknown>
    DestinyVendorGroupDefinition: Record<string, unknown>
    DestinyRewardSourceDefinition: Record<string, unknown>
    DestinyUnlockValueDefinition: Record<string, unknown>
    DestinyRewardMappingDefinition: Record<string, unknown>
    DestinyRewardSheetDefinition: Record<string, unknown>
    DestinyItemCategoryDefinition: Record<string, unknown>
    DestinyDamageTypeDefinition: Record<string, unknown>
    DestinyActivityModeDefinition: Record<string, unknown>
    DestinyMedalTierDefinition: Record<string, unknown>
    DestinyAchievementDefinition: Record<string, unknown>
    DestinyActivityGraphDefinition: Record<string, unknown>
    DestinyActivityInteractableDefinition: Record<string, unknown>
    DestinyBondDefinition: Record<string, unknown>
    DestinyCharacterCustomizationCategoryDefinition: Record<string, unknown>
    DestinyCharacterCustomizationOptionDefinition: Record<string, unknown>
    DestinyCollectibleDefinition: Record<string, unknown>
    DestinyDestinationDefinition: Record<string, unknown>
    DestinyEntitlementOfferDefinition: Record<string, unknown>
    DestinyEquipmentSlotDefinition: Record<string, unknown>
    DestinyEventCardDefinition: Record<string, unknown>
    DestinyStatDefinition: Record<string, unknown>
    DestinyInventoryItemDefinition: Record<string, unknown>
    DestinyInventoryItemLiteDefinition: Record<string, unknown>
    DestinyItemTierTypeDefinition: Record<string, unknown>
    DestinyLocationDefinition: Record<string, unknown>
    DestinyLoreDefinition: Record<string, unknown>
    DestinyMaterialRequirementSetDefinition: Record<string, unknown>
    DestinyMetricDefinition: Record<string, unknown>
    DestinyObjectiveDefinition: Record<string, unknown>
    DestinyPlatformBucketMappingDefinition: Record<string, unknown>
    DestinyPlugSetDefinition: Record<string, unknown>
    DestinyPowerCapDefinition: Record<string, unknown>
    DestinyPresentationNodeDefinition: Record<string, unknown>
    DestinyProgressionDefinition: Record<string, unknown>
    DestinyProgressionLevelRequirementDefinition: Record<string, unknown>
    DestinyRecordDefinition: Record<string, unknown>
    DestinyRewardAdjusterPointerDefinition: Record<string, unknown>
    DestinyRewardAdjusterProgressionMapDefinition: Record<string, unknown>
    DestinyRewardItemListDefinition: Record<string, unknown>
    DestinySackRewardItemListDefinition: Record<string, unknown>
    DestinySandboxPatternDefinition: Record<string, unknown>
    DestinySeasonDefinition: Record<string, unknown>
    DestinySeasonPassDefinition: Record<string, unknown>
    DestinySocketCategoryDefinition: Record<string, unknown>
    DestinySocketTypeDefinition: Record<string, unknown>
    DestinyTraitDefinition: Record<string, unknown>
    DestinyTraitCategoryDefinition: Record<string, unknown>
    DestinyUnlockCountMappingDefinition: Record<string, unknown>
    DestinyUnlockEventDefinition: Record<string, unknown>
    DestinyUnlockExpressionMappingDefinition: Record<string, unknown>
    DestinyVendorDefinition: Record<string, unknown>
    DestinyMilestoneDefinition: Record<string, unknown>
    DestinyActivityModifierDefinition: Record<string, unknown>
    DestinyReportReasonCategoryDefinition: Record<string, unknown>
    DestinyArtifactDefinition: Record<string, unknown>
    DestinyBreakerTypeDefinition: Record<string, unknown>
    DestinyChecklistDefinition: Record<string, unknown>
    DestinyEnergyTypeDefinition: Record<string, unknown>
}